# Travis can building for Linux and macOS
matrix:
  include:
    # To maximise compatibility pick earliest image, OS X 10.10 Yosemite
    - os: osx
      osx_image: xcode6.4
      sudo: required
      language: generic

before_install:
  # OS and default Python info
  - uname -a
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sw_vers; fi
  # TODO: share version numbers with build_python.sh to keep them in sync
  - MACVER=10.9
  - PYVER=python3.7
  - PATCH=3.7.4

install:
  - PROJECT_DIR="$PWD"
  - echo $PROJECT_DIR
  - mkdir upload

script:
  # Download and build Python
  - cd "$PROJECT_DIR"
  - sh build_python.sh

  # Compress and upload it before touching it
  - cd "$PROJECT_DIR"
  - UPLOAD_FILE=python-$PATCH-osx-$MACVER.zip
  - UPLOAD_PATH=upload/$UPLOAD_FILE
  - curl --upload-file $UPLOAD_PATH https://transfer.sh/$UPLOAD_FILE | tee -a output_urls.txt && echo "" >> output_urls.txt

  # Check built Python
  - cd "$PROJECT_DIR"
  - du -sk python-portable/
  - cd python-portable
  - otool -L bin/$PYVER
  - ./bin/$PYVER -c 'import ssl; print(ssl.OPENSSL_VERSION)'
  - ./bin/$PYVER -m pip --version

  # Create a DMG package and upload it
  #- cd "$PROJECT_DIR"
  #- ./build_mu_dmg.sh
  #- curl --upload-file ./upload/Mu-portable.zip https://transfer.sh/Mu-portable.zip | tee -a output_urls.txt && echo "" >> output_urls.txt
  #- curl --upload-file ./upload/Mu-Installer.dmg https://transfer.sh/Mu-Installer.dmg | tee -a output_urls.txt && echo "" >> output_urls.txt

  # Print all uploaded files URLs
  - cd "$PROJECT_DIR"
  - cat output_urls.txt
